/*Auto-generated by resource compiler rc89 v0.0.1. Do not edit manually.
 *Timestamp: 2026.01.04 03:27:36*/
#ifndef CHIP_RESOURCES_H
#define CHIP_RESOURCES_H

typedef enum chip_resource_id {
   CHIP_ICONS_OPEN,
   CHIP_ICONS_PLAYPAUSE,
   CHIP_ICONS_RESET,
   CHIP_ICONS_VOLUME,
   CHIP_ICONS_ROMINFO,
   CHIP_ICONS_ABOUT,
   CHIP_ICONS_ROTATE,
   CHIP_DEFAULT_ROM,
   CHIP_RESOURCE_MAX
} chip_resource_id;

typedef enum chip_resource_loader_kind {
   CHIP_LOADER_RAW,
   CHIP_LOADER_RGBA
} chip_resource_loader_kind;

typedef struct chip_resource_loader_rgba {
   int width;
   int height;
} chip_resource_loader_rgba;

typedef union chip_resource_loader {
   chip_resource_loader_rgba rgba;
} chip_resource_loader;

typedef struct chip_resource {
   const char* name;
   const unsigned char* data;
   int size;
   chip_resource_loader_kind loader_kinds;
   const chip_resource_loader* loader;
} chip_resource;

const chip_resource* chip_get_res(chip_resource_id id);

#endif /*CHIP_RESOURCES_H*/
