/*
 * Auto-generated by romdb v0.0.1. Do not edit manually.
 * Timestamp: 2026.01.02 23:44:01
 */
#ifndef ROMDB_H
#define ROMDB_H
typedef enum romdb_platforms {
   ROMDB_PLATFORM_ORIGINALCHIP8 = 0,
   ROMDB_PLATFORM_HYBRIDVIP = 1,
   ROMDB_PLATFORM_MODERNCHIP8 = 2,
   ROMDB_PLATFORM_CHIP_8X = 3,
   ROMDB_PLATFORM_CHIP48 = 4,
   ROMDB_PLATFORM_SUPERCHIP1 = 5,
   ROMDB_PLATFORM_SUPERCHIP = 6,
   ROMDB_PLATFORM_MAX = 7
} romdb_platforms;
typedef struct romdb_entry {
   const char *sha1;
   romdb_platforms platform;
   int tickrate;
   const char* desc;
} romdb_entry;
extern const romdb_entry romdb_entries[];
const romdb_entry* romdb_get(const char* sha1);
#endif /*ROMDB_H */
